# Generated by Django 5.1.5 on 2025-03-12 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('isbn', models.CharField(help_text='Enter a 10-digit or 13-digit ISBN (numbers only).', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be either 10 or 13 digits long.', regex='^(\\d{10}|\\d{13})$')])),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='english', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='book/images')),
                ('pdf', models.FileField(upload_to='book/pdfs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
                ('genres', models.ManyToManyField(to='home.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_Library')],
            },
        ),
    ]
